language: node_js
node_js:
  - "10"

dist: trusty

env:
  global:
    - SUPPRESS_NO_CONFIG_WARNING=true
    - GK_LOCK_YARN_OPTS='--ignore-engines'

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: "test"
      if: |
        branch ~= /^develop$|^master$|^release\/.+$/ OR \
        type = pull_request OR \
        env(RESTRICT_PUSH_BUILDS) != true
      addons:
        chrome: stable
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH=$HOME/.yarn/bin:$PATH
#        - yarn global add greenkeeper-lockfile@1
      install:
        - yarn --prefer-offline --frozen-lockfile --ignore-engines
        - yarn list --depth=0
#        - greenkeeper-lockfile-update
      before_script:
        - echo "==== PWD ===="
        - pwd
        - ls -ltra /home/travis/build/RCOSDP/RDM-wiki-develop/
        - cat /home/travis/build/RCOSDP/RDM-wiki-develop/.jshintrc
        - echo "============="
        - npm install -g jshint  # JSHintをグローバルにインストール
#        - yarn jshint --config /home/travis/build/RCOSDP/RDM-wiki-develop/.jshintrc /home/travis/build/RCOSDP/RDM-wiki-develop/addons/wiki/static/
#        - yarn jshint --config /home/travis/build/RCOSDP/RDM-wiki-develop/.jshintrc /home/travis/build/RCOSDP/RDM-wiki-develop/website/static/js/pages/
#        - yarn jshint --config /home/travis/build/RCOSDP/RDM-wiki-develop/.jshintrc /home/travis/build/RCOSDP/RDM-wiki-develop/website/static/js/
#        - yarn jshint --config .jshintrc addons/wiki/static/
#        - yarn jshint --config .jshintrc website/static/js/pages/
#        - yarn jshint --config .jshintrc website/static/js/
#        - yarn jshint --config ./code/.jshintrc ./code/addons/wiki/static/*.js
#        - yarn jshint --config ./code/.jshintrc ./code/website/static/js/pages/*.js
#        - yarn jshint --config ./code/.jshintrc ./code/website/static/js/*.js
#        - yarn jshint --config /code/.jshintrc /code/addons/wiki/static/*.js
#        - yarn jshint --config /code/.jshintrc /code/website/static/js/pages/*.js
#        - yarn jshint --config /code/.jshintrc /code/website/static/js/*.js
#        - yarn jshint test
#        - yarn test node-tests
#        - yarn build test
      script:
        - yarn test cover --path ./dist
        - jshint .
#      after_script:
#        - greenkeeper-lockfile-upload
      after_success:
        - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

#    - stage: "deploy handbook"
#      if: |
#        branch = develop AND \
#        type != pull_request AND \
#        env(DEPLOY_KEY) IS present
#      before_install:
#        - curl -o- -L https://yarnpkg.com/install.sh | bash
#        - export PATH=$HOME/.yarn/bin:$PATH
#      install:
#        - yarn --prefer-offline --frozen-lockfile --ignore-engines
#      env:
#        - HANDBOOK_ENABLED=1
#        - MIRAGE_ENABLED=1
#        - SHOW_DEV_BANNER=1
#        - A11Y_AUDIT=0
#        - NODE_OPTIONS=--max-old-space-size=4096
#        - TARGET_BRANCH=gh-pages
#      script:
#        - export ROOT_URL="/${TRAVIS_REPO_SLUG##*\/}/"
#        - export ASSETS_PREFIX="${ROOT_URL}"
#        - ember build --environment=production
#        - cp dist/index.html dist/404.html
#      deploy:
#        provider: script
#        skip-cleanup: true
#        script: scripts/handbook_deploy.sh
#        on:
#          branch: develop
