language: node_js
node_js:
  - "21"
sudo: false

dist: noble

env:
  global:
    - SUPPRESS_NO_CONFIG_WARNING=true
    - GK_LOCK_YARN_OPTS='--ignore-engines'

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: "test"
      if: |
        branch ~= /^develop$|^master$|^release\/.+$/ OR \
        type = pull_request OR \
        env(RESTRICT_PUSH_BUILDS) != true
      addons:
        chrome: stable
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH=$HOME/.yarn/bin:$PATH
      install:
        - yarn --prefer-offline --frozen-lockfile --ignore-engines
        - yarn list --depth=0
      script:
        - yarn add jshint@2.13.6
        - yarn jshint --config .jshintrc ./addons/wiki/static/
        - yarn jshint --config .jshintrc ./website/static/js/pages/
        - yarn jshint --config .jshintrc ./website/static/js/
